### ISSUE TITLE
Trying to createPrivateFolder

### ISSUE THREAD

**Issue by tjones0808** [ardriveapp/ardrive-core-js#234]
Here is my code:

```
async createUserPrivateFolder(userId: string): Promise<string> {
    const folderName = `user_${userId}_private_folder`;

    const driveKey = await this.getDriveKey();
    this.logger.info(`driveKey: ${driveKey}`);

    try {
      // Logic to create a private folder on ArDrive
      const createFolderResult = await this.arDrive.createPrivateFolder({
        folderName: folderName,
        driveKey: driveKey,
        parentFolderId: EID('2632e683-c7cd-48fb-868a-ddd731ee61f5'), // Replace with actual root folder or drive ID
      });

      this.logger.info(`createFolderResult: ${createFolderResult}`);

      // Extract the folder ID from the result
      const destFolderId = createFolderResult.created[0].entityId; // Adjust based on actual response structure

      return destFolderId;
    } catch (error) {
      this.logger.error(error);
      throw error;
    }
  }
```

Here is the error: 

```
{"level":50,"time":1705524497255,"pid":59344,"hostname":"DESKTOP-V3OVRHM","context":"ArdriveService","err":{"type":"ReferenceError","message":"Headers is not defined","stack":"ReferenceError: Headers is not defined\n    at Api.request (C:\\projects\\tjones0808\\heredity\\files\\src\\common\\lib\\api.ts:83:21)\n    at Api.get (C:\\projects\\tjones0808\\heredity\\files\\src\\common\\lib\\api.ts:56:23)\n    at Wallets.getBalance (C:\\projects\\tjones0808\\heredity\\files\\src\\common\\wallets.ts:25:21)\n    at WalletDAO.<anonymous> (C:\\projects\\tjones0808\\heredity\\files\\node_modules\\ardrive-core-js\\lib\\wallet_dao.js:51:80)\n    at Generator.next (<anonymous>)\n    at C:\\projects\\tjones0808\\heredity\\files\\node_modules\\ardrive-core-js\\lib\\wallet_dao.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\projects\\tjones0808\\heredity\\files\\node_modules\\ardrive-core-js\\lib\\wallet_dao.js:4:12)\n    at WalletDAO.getAddressWinstonBalance (C:\\projects\\tjones0808\\heredity\\files\\node_modules\\ardrive-core-js\\lib\\wallet_dao.js:50:16)\n    
at WalletDAO.<anonymous> (C:\\projects\\tjones0808\\heredity\\files\\node_modules\\ardrive-core-js\\lib\\wallet_dao.js:46:25)"},"msg":"Headers is not defined"}
```

**Comment by tjones0808** [comment]
fixed with headers:

```
import fetch, { Headers } from 'node-fetch';

// Assign fetch, Headers, Request, and Response to global scope
global.fetch = fetch;
global.Headers = fetch.Headers;
global.Request = fetch.Request;
global.Response = fetch.Response;
```
